#pragma once

#define IPM_WIDTH 160
#define IPM_HEIGHT 120

#define IPM_LEFT 100
#define IPM_RIGHT 460
#define IPM_TOP 220
#define IPM_BOTTOM 350

#define IPM_INTERPOLATION 0

#define IPM_VP_PORTION 0

#define LINE_WIDTH 2000
#define LINE_HEIGHT 304.8

#define KERNEL_WIDTH 2
#define KERNEL_HEIGHT 2

#define LOWER_QUANTILE 0.975

#define LOCAL_MAXIMA 1

#define GROUPING_TYPE 0

#define BINARIZE 0

#define DETECTION_THRESHOLD 4

#define SMOOTH_SCORES 1

#define R_MIN 10
#define R_MAX 150
#define R_STEP 2
#define THETA_MIN -45
#define THETA_MAX 45
#define THETA_STEP 2

#define GET_END_POINTS 0

#define GROUP 1
#define GROUP_THRESHOLD 10

#define RANSAC 1

#define RANSAC_LINE_NUM_SAMPLES 4
#define RANSAC_LINE_NUM_ITERATIONS 40
#define RANSAC_LINE_NUM_GOOD_FIT 10
#define RANSAC_LINE_THRESHOLD 0.2
#define RANSAC_LINE_SCORE_THRESHOLD 0
#define RANSAC_LINE_BINARIZE 0
#define RANSAC_LINE_WINDOW 15

#define RANSAC_SPLINE_NUM_SAMPLES 4
#define RANSAC_SPLINE_NUM_ITERATIONS 40
#define RANSAC_SPLINE_NUM_GOOD_FIT 10
#define RANSAC_SPLINE_THRESHOLD 0.2
#define RANSAC_SPLINE_SCORE_THRESHOLD 0
#define RANSAC_SPLINE_BINARIZE 0
#define RANSAC_SPLINE_WINDOW 10

#define RANSAC_SPLINE 1
#define RANSAC_SPLINE_DEGREE 3
#define RANSAC_LINE 1

#define RANSAC_SPLINE_STEP 0.1

#define SPLINE_SCORE_JITTER 2
#define SPLINE_SCORE_LENGTH_RATIO 1.5
#define SPLINE_SCORE_ANGLE_RATIO 1.2
#define SPLINE_SCORE_STEP 0.01

#define OVERLAP_THRESHOLD 0.3

#define LOCALIZE_ANGLE_THRESHOLD 0.9
#define LOCALIZE_NUM_LINE_PIXELS 20

#define EXTEND_ANGLE_THRESHOLD 0.86
#define EXTEND_MEAN_DIR_ANGLE_THRESHOLD 0.95
#define EXTEND_LINE_PIXELS_TANGENT 10
#define EXTEND_LINE_PIXELS_NORMAL 20
#define EXTEND_CONT_THRESHOLD 0.35
#define EXTEND_DEVIATION_THRESHOLD 2
#define EXTEND_RECT_TOP 200
#define EXTEND_RECT_BOTTOM 380

#define EXTEND_IPM_ANGLE_THRESHOLD 0.95
#define EXTEND_IPM_MEAN_DIR_ANGLE_THRESHOLD 0.86
#define EXTEND_IPM_LINE_PIXELS_TANGENT 5
#define EXTEND_IPM_LINE_PIXELS_NORMAL 10
#define EXTEND_IPM_CONT_THRESHOLD 0.05
#define EXTEND_IPM_DEVIATION_THRESHOLD 2
#define EXTEND_IPM_RECT_TOP 0
#define EXTEND_IPM_RECT_BOTTOM 118

#define SPLINE_TRACKING_NUM_ABSENT_FRAMES 3
#define SPLINE_TRACKING_NUM_SEEN_FRAMES 5

#define MERGE_SPLINE_THETA_THRESHOLD 0.3
#define MERGE_SPLINE_R_THRESHOLD 15
#define MERGE_SPLINE_MEAN_THETA_THRESHOLD 0.2
#define MERGE_SPLINE_MEAN_R_THRESHOLD 20
#define MERGE_SPLINE_CENTROID_THRESHOLD 80

#define LINE_TRACKING_NUM_ABSENT_FRAMES 2
#define LINE_TRACKING_NUM_SEEN_FRAMES 3

#define MERGE_LINE_THETA_THRESHOLD 0.3
#define MERGE_LINE_R_THRESHOLD 15

#define NUM_STRIPS 1

#define CHECK_SPLINES 1
#define CHECK_SPLINES_CURVENESS_THRESHOLD 0.8
#define CHECK_SPLINES_LENGTH_THRESHOLD 30
#define CHECK_SPLINES_THETA_DIFF_THRESHOLD 0.1
#define CHECK_SPLINES_THETA_THRESHOLD 1.22

#define CHECK_IPM_SPLINES 1
#define CHECK_IPM_SPLINES_CURVENESS_THRESHOLD 0.8
#define CHECK_IPM_SPLINES_LENGTH_THRESHOLD 30
#define CHECK_IPM_SPLINES_THETA_DIFF_THRESHOLD 0.1
#define CHECK_IPM_SPLINES_THETA_THRESHOLD 1.22

#define FINAL_SPLINE_SCORES_THRESHOLD 0

#define USE_GROUND_PLANE 0

#define CHECK_COLOR 0
#define CHECK_COLOR_WINDOW 3
#define CHECK_COLOR_NUM_BINS 16
#define CHECK_COLOR_NUM_YELLOW_MIN 0.3
#define CHECK_COLOR_RG_MIN 1
#define CHECK_COLOR_RG_MAX 40
#define CHECK_COLOR_GB_MIN 10
#define CHECK_COLOR_RB_MIN 25
#define CHECK_COLOR_RBF_THRESHOLD -0.1
#define CHECK_COLOR_RBF 1

#define IPM_WINDOW_CLEAR 0
#define IPM_WINDOW_LEFT 50
#define IPM_WINDOW_RIGHT 110

#define CHECK_LANE_WIDTH 0
#define CHECK_LANE_WIDTH_MEAN 25
#define CHECK_LANE_WIDTH_STD 5