#pragma once

#define STOP_IPM_WIDTH 160
#define STOP_IPM_HEIGHT 120

#define STOP_IPM_LEFT 85
#define STOP_IPM_RIGHT 550
#define STOP_IPM_TOP 50
#define STOP_IPM_BOTTOM 380

#define STOP_IPM_INTERPOLATION 0

#define STOP_IPM_VP_PORTION 0.2

#define STOP_LINE_WIDTH 2000
#define STOP_LINE_HEIGHT 304.8

#define STOP_KERNEL_WIDTH 2
#define STOP_KERNEL_HEIGHT 2

#define STOP_LOWER_QUANTILE 0.975

#define STOP_LOCAL_MAXIMA 1

#define STOP_GROUPING_TYPE 1

#define STOP_BINARIZE 0

#define STOP_DETECTION_THRESHOLD 1

#define STOP_SMOOTH_SCORES 0

#define STOP_R_MIN 0
#define STOP_R_MAX 120
#define STOP_R_STEP 3
#define STOP_THETA_MIN 80
#define STOP_THETA_MAX 100
#define STOP_THETA_STEP 1

#define STOP_GET_END_POINTS 0

#define STOP_GROUP 1
#define STOP_GROUP_THRESHOLD 15

#define STOP_RANSAC 1

#define STOP_RANSAC_LINE_NUM_SAMPLES 5
#define STOP_RANSAC_LINE_NUM_ITERATIONS 10
#define STOP_RANSAC_LINE_NUM_GOOD_FIT 10
#define STOP_RANSAC_LINE_THRESHOLD 0.4
#define STOP_RANSAC_LINE_SCORE_THRESHOLD 0.4
#define STOP_RANSAC_LINE_BINARIZE 0
#define STOP_RANSAC_LINE_WINDOW 15

#define STOP_RANSAC_SPLINE_NUM_SAMPLES 5
#define STOP_RANSAC_SPLINE_NUM_ITERATIONS 10
#define STOP_RANSAC_SPLINE_NUM_GOOD_FIT 10
#define STOP_RANSAC_SPLINE_THRESHOLD 0.4
#define STOP_RANSAC_SPLINE_SCORE_THRESHOLD 0.4
#define STOP_RANSAC_SPLINE_BINARIZE 0
#define STOP_RANSAC_SPLINE_WINDOW 15

#define STOP_RANSAC_SPLINE 0
#define STOP_RANSAC_SPLINE_DEGREE 2
#define STOP_RANSAC_LINE 1

#define STOP_RANSAC_SPLINE_STEP 0.1

#define STOP_SPLINE_SCORE_JITTER 2
#define STOP_SPLINE_SCORE_LENGTH_RATIO 0.5
#define STOP_SPLINE_SCORE_ANGLE_RATIO 0.8
#define STOP_SPLINE_SCORE_STEP 0.1

#define STOP_OVERLAP_THRESHOLD 0.5

#define STOP_LOCALIZE_ANGLE_THRESHOLD 0.7
#define STOP_LOCALIZE_NUM_LINE_PIXELS 20

#define STOP_EXTEND_ANGLE_THRESHOLD 0.7
#define STOP_EXTEND_MEAN_DIR_ANGLE_THRESHOLD 0.7
#define STOP_EXTEND_LINE_PIXELS_TANGENT 5
#define STOP_EXTEND_LINE_PIXELS_NORMAL 20
#define STOP_EXTEND_CONT_THRESHOLD 0.1
#define STOP_EXTEND_DEVIATION_THRESHOLD 2
#define STOP_EXTEND_RECT_TOP 200
#define STOP_EXTEND_RECT_BOTTOM 380

#define STOP_EXTEND_IPM_ANGLE_THRESHOLD 0.9
#define STOP_EXTEND_IPM_MEAN_DIR_ANGLE_THRESHOLD 0.86
#define STOP_EXTEND_IPM_LINE_PIXELS_TANGENT 5
#define STOP_EXTEND_IPM_LINE_PIXELS_NORMAL 10
#define STOP_EXTEND_IPM_CONT_THRESHOLD 0.1
#define STOP_EXTEND_IPM_DEVIATION_THRESHOLD 2
#define STOP_EXTEND_IPM_RECT_TOP 0
#define STOP_EXTEND_IPM_RECT_BOTTOM 380

#define STOP_SPLINE_TRACKING_NUM_ABSENT_FRAMES 3
#define STOP_SPLINE_TRACKING_NUM_SEEN_FRAMES 5

#define STOP_MERGE_SPLINE_THETA_THRESHOLD 0.7
#define STOP_MERGE_SPLINE_R_THRESHOLD 30
#define STOP_MERGE_SPLINE_MEAN_THETA_THRESHOLD 0.7
#define STOP_MERGE_SPLINE_MEAN_R_THRESHOLD 30
#define STOP_MERGE_SPLINE_CENTROID_THRESHOLD 100

#define STOP_LINE_TRACKING_NUM_ABSENT_FRAMES 3
#define STOP_LINE_TRACKING_NUM_SEEN_FRAMES 5

#define STOP_MERGE_LINE_THETA_THRESHOLD 0.2
#define STOP_MERGE_LINE_R_THRESHOLD 30

#define STOP_NUM_STRIPS 1

#define STOP_CHECK_SPLINES 0
#define STOP_CHECK_SPLINES_CURVENESS_THRESHOLD 0.93
#define STOP_CHECK_SPLINES_LENGTH_THRESHOLD 30
#define STOP_CHECK_SPLINES_THETA_DIFF_THRESHOLD 0.1
#define STOP_CHECK_SPLINES_THETA_THRESHOLD 1.22

#define STOP_CHECK_IPM_SPLINES 0
#define STOP_CHECK_IPM_SPLINES_CURVENESS_THRESHOLD 0.85
#define STOP_CHECK_IPM_SPLINES_LENGTH_THRESHOLD 30
#define STOP_CHECK_IPM_SPLINES_THETA_DIFF_THRESHOLD 0.1
#define STOP_CHECK_IPM_SPLINES_THETA_THRESHOLD 1.4

#define STOP_FINAL_SPLINE_SCORES_THRESHOLD 0

#define STOP_USE_GROUND_PLANE 1

#define STOP_CHECK_COLOR 0
#define STOP_CHECK_COLOR_WINDOW 3
#define STOP_CHECK_COLOR_NUM_BINS 16
#define STOP_CHECK_COLOR_NUM_YELLOW_MIN 0.5
#define STOP_CHECK_COLOR_RG_MIN 1
#define STOP_CHECK_COLOR_RG_MAX 40
#define STOP_CHECK_COLOR_GB_MIN 15
#define STOP_CHECK_COLOR_RB_MIN 25
#define STOP_CHECK_COLOR_RBF_THRESHOLD -0.05
#define STOP_CHECK_COLOR_RBF 1

#define STOP_IPM_WINDOW_CLEAR 0
#define STOP_IPM_WINDOW_LEFT 50
#define STOP_IPM_WINDOW_RIGHT 110

#define STOP_CHECK_LANE_WIDTH 0
#define STOP_CHECK_LANE_WIDTH_MEAN 25
#define STOP_CHECK_LANE_WIDTH_STD 5